# Reads openclaw/.env, writes ~/.openclaw/.env
# Default: gpt2giga proxy at http://127.0.0.1:8090/v1 (start gpt2giga before gateway).
# Set USE_GPT2GIGA_PROXY=false for legacy direct GigaChat OAuth (short-lived token).
$ErrorActionPreference = "Stop"
$openclawDir = Split-Path $PSScriptRoot -Parent
$projEnv = Join-Path $openclawDir ".env"

Get-Content $projEnv | ForEach-Object {
    if ($_ -match '^\s*#' -or $_ -notmatch '=') { return }
    $pair = $_ -split '=', 2
    if ($pair.Count -eq 2) {
        $k = $pair[0].Trim()
        $v = $pair[1].Trim().Trim('"')
        if ($k) { [Environment]::SetEnvironmentVariable($k, $v, "Process") }
    }
}

$useProxy = $env:USE_GPT2GIGA_PROXY
if ($null -eq $useProxy -or $useProxy -eq '' -or $useProxy -eq '1' -or $useProxy -eq 'true') {
    $port = if ($env:GPT2GIGA_PORT) { $env:GPT2GIGA_PORT } else { '8090' }
    $dummyKey = if ($env:GPT2GIGA_CLIENT_OPENAI_KEY) { $env:GPT2GIGA_CLIENT_OPENAI_KEY } else { 'sk-openclaw-gpt2giga-local' }
    $stateDir = Join-Path $env:USERPROFILE ".openclaw"
    if (-not (Test-Path $stateDir)) { New-Item -ItemType Directory -Path $stateDir -Force | Out-Null }
    $userEnv = Join-Path $stateDir ".env"
    @(
        "# Generated by apply-env-to-openclaw.ps1 (gpt2giga proxy)",
        "TELEGRAM_BOT_TOKEN=$($env:TELEGRAM_BOT_TOKEN)",
        "OPENAI_API_KEY=$dummyKey",
        "OPENAI_BASE_URL=http://127.0.0.1:$port/v1"
    ) | Set-Content -Path $userEnv -Encoding UTF8
    $extra = Get-Content $userEnv -Raw
    if ($extra -notmatch 'NODE_OPTIONS=') {
        Add-Content -Path $userEnv -Value "NODE_OPTIONS=--use-system-ca" -Encoding UTF8
    }
    Write-Host "OK: $userEnv (gpt2giga -> http://127.0.0.1:$port/v1)" -ForegroundColor Green
}
else {
    $cid = $env:GIGACHAT_CLIENT_ID
    $sec = $env:GIGACHAT_CLIENT_SECRET
    $scope = if ($env:GIGACHAT_SCOPE) { $env:GIGACHAT_SCOPE } else { "GIGACHAT_API_PERS" }
    if (-not $cid -or -not $sec) { throw "Missing GIGACHAT_CLIENT_ID or GIGACHAT_CLIENT_SECRET in .env" }

    $basic = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes("${cid}:${sec}"))
    $rqUid = [guid]::NewGuid().ToString()
    $resp = Invoke-RestMethod -Uri "https://ngw.devices.sberbank.ru:9443/api/v2/oauth" -Method Post -Headers @{
        "Content-Type" = "application/x-www-form-urlencoded"
        "Accept" = "application/json"
        "RqUID" = $rqUid
        "Authorization" = "Basic $basic"
    } -Body "scope=$scope" -TimeoutSec 30

    $at = $resp.access_token
    if (-not $at) { throw "GigaChat OAuth returned no access_token" }

    $stateDir = Join-Path $env:USERPROFILE ".openclaw"
    if (-not (Test-Path $stateDir)) { New-Item -ItemType Directory -Path $stateDir -Force | Out-Null }

    $userEnv = Join-Path $stateDir ".env"
    @(
        "# Generated by apply-env-to-openclaw.ps1 - do not commit",
        "TELEGRAM_BOT_TOKEN=$($env:TELEGRAM_BOT_TOKEN)",
        "OPENAI_API_KEY=$at",
        "OPENAI_BASE_URL=https://gigachat.devices.sberbank.ru/api/v1"
    ) | Set-Content -Path $userEnv -Encoding UTF8
    $extra = Get-Content $userEnv -Raw
    if ($extra -notmatch 'NODE_OPTIONS=') {
        Add-Content -Path $userEnv -Value "NODE_OPTIONS=--use-system-ca" -Encoding UTF8
    }
    Write-Host "OK: $userEnv (direct GigaChat OAuth)"
}

# telegram-user (skill invoke.ps1 / gateway): не перезаписываем весь .env — дописываем из openclaw/.env
$userEnvFinal = Join-Path $env:USERPROFILE ".openclaw\.env"
if (Test-Path $userEnvFinal) {
    if ($env:TELEGRAM_USER_BASE_URL) {
        $c = Get-Content $userEnvFinal -Raw
        if ($c -notmatch '(?m)^TELEGRAM_USER_BASE_URL=') {
            Add-Content -Path $userEnvFinal -Value "TELEGRAM_USER_BASE_URL=$($env:TELEGRAM_USER_BASE_URL)" -Encoding UTF8
        }
    }
    if ($env:TELEGRAM_USER_AGENT_TOKEN) {
        $c = Get-Content $userEnvFinal -Raw
        if ($c -notmatch '(?m)^TELEGRAM_USER_AGENT_TOKEN=') {
            Add-Content -Path $userEnvFinal -Value "TELEGRAM_USER_AGENT_TOKEN=$($env:TELEGRAM_USER_AGENT_TOKEN)" -Encoding UTF8
        }
    }
}
