# Starts gpt2giga OpenAI->GigaChat proxy (reads openclaw/.env, writes secrets only to .gpt2giga.runtime.env).
$ErrorActionPreference = "Stop"
$openclawDir = Split-Path $PSScriptRoot -Parent
$envFile = Join-Path $openclawDir ".env"
if (-not (Test-Path $envFile)) { throw "Missing $envFile" }

Get-Content $envFile | ForEach-Object {
    if ($_ -match '^\s*#' -or $_ -notmatch '=') { return }
    $pair = $_ -split '=', 2
    if ($pair.Count -eq 2) {
        $k = $pair[0].Trim()
        $v = $pair[1].Trim().Trim('"')
        if ($k) { Set-Item -Path "env:$k" -Value $v }
    }
}

$cid = $env:GIGACHAT_CLIENT_ID
$sec = $env:GIGACHAT_CLIENT_SECRET
if (-not $cid -or -not $sec) { throw "GIGACHAT_CLIENT_ID / GIGACHAT_CLIENT_SECRET required in .env" }

$scope = if ($env:GIGACHAT_SCOPE) { $env:GIGACHAT_SCOPE } else { "GIGACHAT_API_PERS" }
$port = if ($env:GPT2GIGA_PORT) { [int]$env:GPT2GIGA_PORT } else { 8090 }
$credB64 = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes("${cid}:${sec}"))

# Python/httpx to Sber APIs: same class of errors as Node SELF_SIGNED_CERT_IN_CHAIN unless OS CA or explicit bundle.
# If .env has GIGACHAT_VERIFY_SSL_CERTS=false, use it; on Windows if unset, default to False (set true only if you added proper CA).
$verifySsl = "True"
if ($env:GIGACHAT_VERIFY_SSL_CERTS) {
    $v = $env:GIGACHAT_VERIFY_SSL_CERTS.Trim().ToLowerInvariant()
    if ($v -eq "false" -or $v -eq "0" -or $v -eq "no") { $verifySsl = "False" }
    elseif ($v -eq "true" -or $v -eq "1" -or $v -eq "yes") { $verifySsl = "True" }
}
elseif ($env:OS -match "Windows") {
    $verifySsl = "False"
}

$runtimeEnv = Join-Path $openclawDir ".gpt2giga.runtime.env"
@(
    "# Generated by start-gpt2giga.ps1 - do not commit",
    "GIGACHAT_CREDENTIALS=$credB64",
    "GIGACHAT_SCOPE=$scope",
    "GIGACHAT_MODEL=GigaChat",
    "GIGACHAT_VERIFY_SSL_CERTS=$verifySsl",
    "GIGACHAT_BASE_URL=https://gigachat.devices.sberbank.ru/api/v1",
    "GPT2GIGA_HOST=127.0.0.1",
    "GPT2GIGA_PORT=$port",
    "GPT2GIGA_MODE=DEV",
    "GPT2GIGA_ENABLE_API_KEY_AUTH=False",
    "GPT2GIGA_PASS_MODEL=False",
    "GPT2GIGA_PASS_TOKEN=False",
    "GPT2GIGA_LOG_LEVEL=INFO"
) | Set-Content -Path $runtimeEnv -Encoding UTF8

function Find-Gpt2GigaExe {
    $cmd = Get-Command gpt2giga -ErrorAction SilentlyContinue
    if ($cmd -and $cmd.Path) { return $cmd.Path }
    foreach ($p in @(
            (Join-Path $env:LOCALAPPDATA "Programs\Python\Python312\Scripts\gpt2giga.exe"),
            (Join-Path $env:LOCALAPPDATA "Programs\Python\Python311\Scripts\gpt2giga.exe"),
            (Join-Path $env:USERPROFILE "anaconda3\Scripts\gpt2giga.exe"),
            (Join-Path $env:USERPROFILE "miniconda3\Scripts\gpt2giga.exe")
        )) {
        if (Test-Path $p) { return $p }
    }
    throw "gpt2giga not found. Run: .\scripts\install-gpt2giga.ps1"
}

& (Join-Path $PSScriptRoot "stop-gpt2giga.ps1") -Port $port

$exe = Find-Gpt2GigaExe
Write-Host "Starting gpt2giga on 127.0.0.1:$port ..." -ForegroundColor Cyan
Start-Process -FilePath $exe -ArgumentList @('--env-path', $runtimeEnv) -WorkingDirectory $openclawDir -WindowStyle Hidden

$ready = $false
for ($i = 0; $i -lt 45; $i++) {
    $listen = Get-NetTCPConnection -LocalPort $port -State Listen -ErrorAction SilentlyContinue
    if ($listen) {
        $ready = $true
        break
    }
    Start-Sleep -Seconds 1
}
if (-not $ready) { throw "gpt2giga did not listen on port $port within 45s" }
Write-Host "OK: gpt2giga listening on http://127.0.0.1:$port/v1" -ForegroundColor Green
